FloristManagement/Models/Occasion.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloristManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Occasion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Occasion()
        {
            this.Bouquets = new HashSet<Bouquet>();
        }
    
        public int OccasionID { get; set; }
        public string Name { get; set; }
        public string ImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bouquet> Bouquets { get; set; }
    }
}

FloristManagement/Areas/Admin/Controllers/OccasionsController.cs
using FloristManagement.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace FloristManagement.Areas.Admin.Controllers
{
    public class OccasionsController : Controller
    {
        private FlowersEntities db = new FlowersEntities();

        // GET: Admin/Occasions
        public ActionResult Index()
        {
            return View(db.Occasions.ToList());
        }

        // GET: Admin/Occasions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Occasion occasion = db.Occasions.Find(id);
            if (occasion == null)
            {
                return HttpNotFound();
            }
            return View(occasion);
        }

        // GET: Admin/Occasions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Occasions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create(Occasion occasion, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                if (ImageFile != null && ImageFile.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(ImageFile.FileName);
                    var filePath = Path.Combine(Server.MapPath("~/Uploads/"), fileName);
                    ImageFile.SaveAs(filePath);
                    occasion.ImagePath = "~/Uploads/" + fileName;
                }

                db.Occasions.Add(occasion);
                db.SaveChanges();

                return RedirectToAction("Index");

            }

            return View(occasion);
        }

        // GET: Admin/Occasions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Occasion occasion = db.Occasions.Find(id);
            if (occasion == null)
            {
                return HttpNotFound();
            }
            return View(occasion);
        }

        // POST: Admin/Occasions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit(Occasion occasion, HttpPostedFileBase ImageFile)
        {
            var existingProduct = db.Occasions.Find(occasion.OccasionID);

            existingProduct.Name = occasion.Name;

            if (ImageFile != null && ImageFile.ContentLength > 0)
            {
                var fileName = Path.GetFileName(ImageFile.FileName);
                var filePath = Path.Combine(Server.MapPath("~/Uploads/"), fileName);
                ImageFile.SaveAs(filePath);
                existingProduct.ImagePath = "~/Uploads/" + fileName;
            }

            db.Entry(existingProduct).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");

        }

        // GET: Admin/Occasions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Occasion occasion = db.Occasions.Find(id);
            if (occasion == null)
            {
                return HttpNotFound();
            }
            return View(occasion);
        }

        // POST: Admin/Occasions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Occasion occasion = db.Occasions.Find(id);
            db.Occasions.Remove(occasion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FloristManagement/Areas/Admin/Views/Occasions/Create.cshtml
@model FloristManagement.Models.Occasion

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml";
}

<main class="app-content">
    <div class="app-title">
        <ul class="app-breadcrumb breadcrumb side">
            <li class="breadcrumb-item active"><a href="#"><b>Create a occasion</b></a></li>
        </ul>
        <div id="clock"></div>
    </div>
    @using (Html.BeginForm("Create", "Occasions", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="form-group col-md-3">
            <label class="control-label">Tên sự kiện</label>
            <input type="text" name="Name" class="form-control" />
        </div>

        <div class="form-group col-md-12">
            <label class="control-label">Ảnh sự kiện</label>
            <div id="myfileupload">
                <input type="file" id="ImageFile" name="ImageFile" onchange="readURL(this);" />
            </div>
            <div id="thumbbox">
                <img height="450" width="400" alt="Thumb image" id="thumbimage" style="display: none" />
                <a class="removeimg" href="javascript:"></a>
            </div>
            <div id="boxchoice">
                <a href="javascript:" class="Choicefile"><i class="fas fa-cloud-upload-alt"></i> Chọn ảnh</a>
                <p style="clear:both"></p>
            </div>
        </div>
        <div class="form-group">
            <input class=" form-control col-md-2" type="submit" value="Create" />
            <hr />
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    }
</main>

FloristManagement/Areas/Admin/Views/Occasions/Delete.cshtml
@model FloristManagement.Models.Occasion

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml";
}

<div class="main-body">
    <div class="page-wrapper">
        <!-- [ breadcrumb ] start -->
        <main class="app-content">
            <div class="app-title">
                <ul class="app-breadcrumb breadcrumb side">
                    <li class="breadcrumb-item active"><a href="#"><b>Delete an occasion</b></a></li>
                </ul>
                <div id="clock"></div>
            </div>
            <div>
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                    <dt>
                        Image
                    </dt>
                    <dt>
                        <img src="@Url.Content(Model.ImagePath)" width="150" />
                    </dt>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-default" /> |
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                }
            </div>
        </main>
    </div>
</div>

FloristManagement/Areas/Admin/Views/Occasions/Details.cshtml
@model FloristManagement.Models.Occasion

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Occasion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.OccasionID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FloristManagement/Areas/Admin/Views/Occasions/Edit.cshtml
@model FloristManagement.Models.Occasion

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml";
}

<main class="app-content">
    <div class="app-title">
        <ul class="app-breadcrumb breadcrumb side">
            <li class="breadcrumb-item active"><a href="#"><b>Edit an occasion</b></a></li>
        </ul>
        <div id="clock"></div>
    </div>
    @using (Html.BeginForm("Edit", "Occasions", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input name="OccasionID" type="hidden" value="@Model.OccasionID" />
        <div class="form-group col-md-3">
            <label class="control-label">Tên sự kiện</label>
            <input type="text" name="Name" class="form-control" value="@Model.Name" />
        </div>

        <div class="form-group col-md-12">
            <label class="control-label">Ảnh sự kiện</label>
            <div id="myfileupload">
                <input type="file" id="ImageFile" name="ImageFile" onchange="readURL(this);" />
            </div>
            <div id="thumbbox">
                <img height="450" width="400" alt="Thumb image" id="thumbimage" style="display: none" />
                <a class="removeimg" href="javascript:"></a>
            </div>
            <div id="boxchoice">
                <a href="javascript:" class="Choicefile"><i class="fas fa-cloud-upload-alt"></i> Chọn ảnh</a>
                <p style="clear:both"></p>
            </div>
            <img src="@Url.Content(Model.ImagePath)" width="100px" />
        </div>
        <div class="form-group">
            <input class=" form-control col-md-2" type="submit" value="Create" />
            <hr />
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    }
</main>

FloristManagement/Areas/Admin/Views/Occasions/Index.cshtml
@model IEnumerable<FloristManagement.Models.Occasion>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml";
}

<div class="main-body">
    <div class="page-wrapper">
        <!-- [ breadcrumb ] start -->
        <main class="app-content">
            <div class="app-title">
                <ul class="app-breadcrumb breadcrumb side">
                    <li class="breadcrumb-item active"><a href="#"><b>List of occasions</b></a></li>
                </ul>
                <div id="clock"></div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="tile">
                        <div class="tile-body">
                            <div class="row element-button">
                                <div class="col-sm-3">
                                    <a class="btn btn-delete btn-sm print-file" type="button" title="In" onclick="myApp.printTable()">
                                        <i class="fas fa-print"></i> In dữ liệu
                                    </a>
                                </div>
                                <div class="col-sm-3">
                                    <a class="btn btn-delete btn-sm print-file js-textareacopybtn" type="button" title="Sao chép">
                                        <i class="fas fa-copy"></i> Sao chép
                                    </a>
                                </div>

                                <div class="col-sm-3">
                                    <a class="btn btn-excel btn-sm" href="" title="In"><i class="fas fa-file-excel"></i> Xuất Excel</a>
                                </div>
                                <div class="col-sm-3">
                                    <a class="btn btn-delete btn-sm pdf-file" type="button" title="In" onclick="myFunction(this)">
                                        <i class="fas fa-file-pdf"></i> Xuất PDF
                                    </a>
                                </div>
                            </div>
                            <table class="table table-hover table-bordered" id="sampleTable">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Name</th>
                                        <th>Image</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        int i = 1;
                                    }
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@(i++)</td>
                                            <td>
                                                @item.Name
                                            </td>
                                            <td>
                                                <img src="@Url.Content(item.ImagePath)" alt="Uploaded Image" width="100px" />
                                            </td>
                                            <td>
                                                <a href="/Admin/Occasions/Delete/@item.OccasionID">
                                                    <button class="btn btn-default btn-sm trash" type="button" title="Xóa"><i class="fas fa-trash-alt"></i> </button>
                                                </a>
                                                <a href="/Admin/Occasions/Edit/@item.OccasionID">
                                                    <button class="btn btn-default btn-sm edit" type="button" title="Sửa"><i class="fa fa-edit"></i></button>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <!-- [ Main Content ] end -->
    </div>
</div>
<p>
    <button class="btn btn-default">
        @Html.ActionLink("Create New", "Create")
    </button>
</p>