FloristManagement/Models/Gallery.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloristManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public int id { get; set; }
        public string ImagePath { get; set; }
    }
}

FloristManagement/Areas/Admin/Controllers/GalleriesController.cs
using FloristManagement.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FloristManagement.Areas.Admin.Controllers
{
    public class GalleriesController : Controller
    {
        private FlowersEntities db = new FlowersEntities();

        // GET: Admin/Galleries
        public ActionResult Index()
        {
            return View(db.Galleries.ToList());
        }

        // GET: Admin/Galleries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gallery gallery = db.Galleries.Find(id);
            if (gallery == null)
            {
                return HttpNotFound();
            }
            return View(gallery);
        }

        // GET: Admin/Galleries/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Galleries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create(Gallery gallery, HttpPostedFileBase[] ImageFiles)
        {
            if (ModelState.IsValid)
            {
                foreach (var file in ImageFiles)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        string filename = Path.GetFileName(file.FileName);
                        string path = Path.Combine(Server.MapPath("~/Uploads/Galleries/"), filename);
                        file.SaveAs(path);
                        gallery.ImagePath = "~/Uploads/Galleries/" + filename;
                    }
                    db.Galleries.Add(gallery);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }

            return View(gallery);
        }

        // GET: Admin/Galleries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gallery gallery = db.Galleries.Find(id);
            if (gallery == null)
            {
                return HttpNotFound();
            }
            return View(gallery);
        }

        // POST: Admin/Galleries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit(Gallery gallery, HttpPostedFileBase ImageFile)
        {
            var existingProduct = db.Galleries.Find(gallery.id);

            if (ImageFile != null && ImageFile.ContentLength > 0)
            {
                var fileName = Path.GetFileName(ImageFile.FileName);
                var filePath = Path.Combine(Server.MapPath("~/Uploads/"), fileName);
                ImageFile.SaveAs(filePath);
                existingProduct.ImagePath = "~/Uploads/" + fileName;
            }

            db.Entry(existingProduct).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: Admin/Galleries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gallery gallery = db.Galleries.Find(id);
            if (gallery == null)
            {
                return HttpNotFound();
            }
            return View(gallery);
        }

        // POST: Admin/Galleries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Gallery gallery = db.Galleries.Find(id);
            db.Galleries.Remove(gallery);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FloristManagement/Controllers/GalleryController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FloristManagement.Models;

namespace FloristManagement.Controllers
{
    public class GalleryController : Controller
    {
        FlowersEntities db = new FlowersEntities();
        // GET: Gallery
        public ActionResult Index(int? page)
        {
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            var galleries = db.Galleries.ToList();

            return View(galleries.ToPagedList(pageNumber, pageSize));
        }
    }
}

FloristManagement/Areas/Admin/Views/Galleries/Create.cshtml
@model FloristManagement.Models.Gallery

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml";
}

<main class="app-content">
    <div class="app-title">
        <ul class="app-breadcrumb breadcrumb side">
            <li class="breadcrumb-item active"><a href="#"><b>Create a gallery</b></a></li>
        </ul>
        <div id="clock"></div>
    </div>
    @using (Html.BeginForm("Create", "Galleries", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        <div class="form-group col-md-12">
            <label class="control-label">Images</label>
            <div id="myfileupload">
                <input type="file" id="ImageFiles" name="ImageFiles" multiple onchange="readURL(this);" />
            </div>
            <div id="thumbbox">
                <img height="450" width="400" alt="Thumb image" id="thumbimage" style="display: none" />
                <a class="removeimg" href="javascript:"></a>
            </div>
            <div id="boxchoice">
                <a href="javascript:" class="Choicefile"><i class="fas fa-cloud-upload-alt"></i> Chọn ảnh</a>
                <p style="clear:both"></p>
            </div>
        </div>
        <div class="form-group">
            <input class=" form-control col-md-2" type="submit" value="Create" />
            <hr />
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    }
</main>

FloristManagement/Areas/Admin/Views/Galleries/Delete.cshtml
@model FloristManagement.Models.Gallery

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml";
}

<div class="main-body">
    <div class="page-wrapper">
        <!-- [ breadcrumb ] start -->
        <main class="app-content">
            <div class="app-title">
                <ul class="app-breadcrumb breadcrumb side">
                    <li class="breadcrumb-item active"><a href="#"><b>Delete a gallery</b></a></li>
                </ul>
                <div id="clock"></div>
            </div>
            <div>
                <dl class="dl-horizontal">
                    <dt>
                        Image
                    </dt>
                    <dt>
                        <img src="@Url.Content(Model.ImagePath)" width="150" />
                    </dt>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-default" /> |
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                }
            </div>
        </main>
    </div>
</div>

FloristManagement/Areas/Admin/Views/Galleries/Details.cshtml
@model FloristManagement.Models.Gallery

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Gallery</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FloristManagement/Areas/Admin/Views/Galleries/Edit.cshtml
@model FloristManagement.Models.Gallery

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml";
}

<main class="app-content">
    <div class="app-title">
        <ul class="app-breadcrumb breadcrumb side">
            <li class="breadcrumb-item active"><a href="#"><b>Edit an gallery</b></a></li>
        </ul>
        <div id="clock"></div>
    </div>
    @using (Html.BeginForm("Edit", "Galleries", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input name="OccasionID" type="hidden" value="@Model.id" />
        <div class="form-group col-md-12">
            <label class="control-label">Ảnh gallery</label>
            <div id="myfileupload">
                <input type="file" id="ImageFile" name="ImageFile" onchange="readURL(this);" />
            </div>
            <div id="thumbbox">
                <img height="450" width="400" alt="Thumb image" id="thumbimage" style="display: none" />
                <a class="removeimg" href="javascript:"></a>
            </div>
            <div id="boxchoice">
                <a href="javascript:" class="Choicefile"><i class="fas fa-cloud-upload-alt"></i> Chọn ảnh</a>
                <p style="clear:both"></p>
            </div>
            <img src="@Url.Content(Model.ImagePath)" width="100px" />
        </div>
        <div class="form-group">
            <input class=" form-control col-md-2" type="submit" value="Create" />
            <hr />
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    }
</main>

FloristManagement/Areas/Admin/Views/Galleries/Index.cshtml
@model IEnumerable<FloristManagement.Models.Gallery>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml";
}

<div class="main-body">
    <div class="page-wrapper">
        <!-- [ breadcrumb ] start -->
        <main class="app-content">
            <div class="app-title">
                <ul class="app-breadcrumb breadcrumb side">
                    <li class="breadcrumb-item active"><a href="#"><b>List of galleries</b></a></li>
                </ul>
                <div id="clock"></div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="tile">
                        <div class="tile-body">
                            <div class="row element-button">
                                <div class="col-sm-3">
                                    <a class="btn btn-delete btn-sm print-file" type="button" title="In" onclick="myApp.printTable()">
                                        <i class="fas fa-print"></i> In dữ liệu
                                    </a>
                                </div>
                                <div class="col-sm-3">
                                    <a class="btn btn-delete btn-sm print-file js-textareacopybtn" type="button" title="Sao chép">
                                        <i class="fas fa-copy"></i> Sao chép
                                    </a>
                                </div>

                                <div class="col-sm-3">
                                    <a class="btn btn-excel btn-sm" href="" title="In"><i class="fas fa-file-excel"></i> Xuất Excel</a>
                                </div>
                                <div class="col-sm-3">
                                    <a class="btn btn-delete btn-sm pdf-file" type="button" title="In" onclick="myFunction(this)">
                                        <i class="fas fa-file-pdf"></i> Xuất PDF
                                    </a>
                                </div>
                            </div>
                            <table class="table table-hover table-bordered" id="sampleTable">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Image</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        int i = 1;
                                    }
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@(i++)</td>
                                            <td>
                                                <img src="@Url.Content(item.ImagePath)" alt="Uploaded Image" width="100px" />
                                            </td>
                                            <td>
                                                <a href="/Admin/Galleries/Delete/@item.id">
                                                    <button class="btn btn-default btn-sm trash" type="button" title="Xóa"><i class="fas fa-trash-alt"></i> </button>
                                                </a>
                                                <a href="/Admin/Galleries/Edit/@item.id">
                                                    <button class="btn btn-default btn-sm edit" type="button" title="Sửa"><i class="fa fa-edit"></i></button>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <!-- [ Main Content ] end -->
    </div>
</div>
<p>
    <button class="btn btn-default">
        @Html.ActionLink("Create New", "Create")
    </button>
</p>